[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# for cosmic collapse:
# Add `kcv_cosmic_collapse_calculate` field to context,
# as context.after is too broad as the sole flag and can cause excessive triggers.
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "G.FUNCS.draw_from_hand_to_discard()"
position = 'before'
match_indent = true
payload = '''

for i, joker_card in ipairs(G.jokers.cards) do
    joker_card:calculate_joker({kcv_cosmic_collapse_calculate=true})
end
delay(0.3)

'''

# add `kcv_juice_card_until` field to context.individual return object
# Provides an appropriate timeslot to call juice_card_until during  context.individual
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "if effects[ii].extra then"
position = 'before'
match_indent = true
payload = '''

if effects[ii].kcv_juice_card_until then
    G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
            local eval = function(card)
                return true
            end
            juice_card_until(effects[ii].card, eval, true)
            return true
        end
    }))
end

'''

# Luck of the Irish (mult effect)
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "if pseudorandom('lucky_mult') < G.GAME.probabilities.normal/5 then"
position = 'at'
match_indent = true
payload = '''

local kcv_irish_factor = 1
if self:is_suit("Clubs") then
    for i, joker in ipairs(G.jokers.cards) do
        if joker.ability.name == 'Luck of the Irish' then
            kcv_irish_factor = kcv_irish_factor * 4
        end
    end
end
if pseudorandom('lucky_mult') < (G.GAME.probabilities.normal * kcv_irish_factor)/5 then

'''

# Luck of the Irish (money effect)
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "if pseudorandom('lucky_money') < G.GAME.probabilities.normal/15 then"
position = 'at'
match_indent = true
payload = '''

local kcv_irish_factor = 1
if self:is_suit("Clubs") then
    for i, joker in ipairs(G.jokers.cards) do
        if joker.ability.name == 'Luck of the Irish' then
            kcv_irish_factor = kcv_irish_factor * 4
        end
    end
end
if pseudorandom('lucky_money') < (G.GAME.probabilities.normal * kcv_irish_factor)/15 then

'''
