[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# cosmic collapse
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "G.FUNCS.draw_from_hand_to_discard()"
position = 'before'
match_indent = true
payload = '''

for i, joker_card in ipairs(G.jokers.cards) do
    joker_card:calculate_joker({kcv_cosmic_collapse_calculate=true})
end
delay(0.3)

'''

# run event on play_area
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "if effects[ii].extra then"
position = 'before'
match_indent = true
payload = '''

if effects[ii].kcv_juice_card_until then
    G.E_MANAGER:add_event(Event({
        trigger = 'immediate',
        func = function()
            local eval = function(card)
                return true
            end
            juice_card_until(effects[ii].card, eval, true)
            return true
        end
    }))
end

'''
